name: grocery_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  #Font awesome icons
  font_awesome_flutter: ^9.1.0
  #Flutter Slidable widget
  flutter_slidable: ^0.6.0
  #Firebase
  firebase_core: ^1.3.0
  #Firebase login
  firebase_auth: ^1.4.1
  #Firebase Database
  cloud_firestore: ^2.2.2
  #Firebase storage
  firebase_storage: ^8.1.3
  #Firebase messaging:  for notifications
  firebase_messaging: ^10.0.2
  #image picker
  file_picker: ^3.0.2+2
  # State Management and Streams manipulations
  provider: ^5.0.0
  rxdart: ^0.27.1
  # Local Storage: For dark mode
  get_storage: ^2.0.3
  #Show svg images
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.6
  #Flutter toast
  fluttertoast: ^8.0.7
  #Http plugin for notifications and payment
  http: ^0.13.3
  #UIs
  numberpicker: ^2.1.1
  #Image resizer to reduce upload size
  flutter_native_image: ^0.0.6
  #Geocoding plugin to get location from address
  geocoding: ^2.0.0
  #Map launcher plugin to show address in map
  map_launcher: ^2.0.0
  cloud_functions: ^3.0.4
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Splash Screen
  flutter_native_splash: ^1.2.0
  #Icons
  flutter_launcher_icons: ^0.9.1

flutter_native_splash:
  image: images/logo_splash.png
  color: "#ffffff"
  color_dark: "#404E5A"
  android_disable_fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/empty_cart.svg
    - images/error.svg
    - images/nothing_found.svg
    - images/reminder.svg
    - images/success.svg
    - images/category.svg
    - images/delivery_boy.svg
    - images/no_delivery_found.svg
    - images/map.svg
    - images/logo.png
    - images/logo_splash.png
    - images/upload_image.png
    - images/stripe.png
    - images/profile.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
